name: Build and Push Docker images into AWS ECR
on: [push]
env:
  AWS_REGION: ap-south-1
  AWS_ECR_REPOSITORY: github-python-app
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
jobs:
  push_docker_image_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION
      - name: ECR login
        id: ecr-id
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push docker images to ecr 
        env:
          ECR_REGISTRY: ${{ steps.ecr-id.outputs.ECR_REGISTRY }}
        run: |
          docker build -t $ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG